#!/bin/bash
#
# Bittern Cache.
#
# Copyright(c) 2013, 2014, 2015, Twitter, Inc., All rights reserved.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU General Public License,
# version 2, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
#
SOURCE_FILES=$*

GIT_BRANCH=`git branch | fgrep '*' | tr '\n' ' ' | sed -e 's/[#"*]//g' -e "s/'//g"`
GIT_DESCRIBE=`git describe --all | tr '\n' ' ' | sed -e 's/[#"*]//g' -e "s/'//g"`
GIT_STATUS=`git status | tr '\n' ' ' | sed -e 's/[#"*]//g' -e "s/'//g"`
GIT_TAG=`git tag | grep "20[0-9][0-9]_[01][0-9]_[0123][0-9]_" | tail -1`

echo '/*'
echo ' *' this file is autogenerated -- do not modify
echo ' *'
echo ' *' generated on: `date`
echo ' *'
echo ' */'

echo ''

echo const char cache_git_generated[] = \"`date +'%Y-%m-%d-%T'`\"\;
echo ''
echo const char cache_git_branch[] = \"$GIT_BRANCH\"\;
echo ''
echo const char cache_git_describe[] = \"$GIT_DESCRIBE\"\;
echo ''
echo const char cache_git_status[] = \"$GIT_STATUS\"\;
echo ''
echo const char cache_git_tag[] = \"$GIT_TAG\"\;
echo ''
echo -n const char cache_git_files[] = \"
for f in $SOURCE_FILES
do
        __git_log=`git log --abbrev-commit $f | head -1 | awk '{ print $2; }'`
        __f_basename=`basename $f`
        echo -n "$__f_basename=$__git_log "
done
echo \"\;
